### ISSUE TITLE
mistake?

### ISSUE THREAD

**Issue by winkingsl** [sheaivey/rx5808-pro-diversity#107]
change 780 string rx5808-pro-diversity.ino file
`if (channelIndex > CHANNEL_MAX_INDEX) // negative overflow`
to 
` if (channelIndex < CHANNEL_MIN_INDEX) // negative overflow`

**Comment by sheaivey** [comment]
**uint8_t channelIndex** is an unsigned variable meaning -1 will equal 255.
Therefor this is no mistake and the comment reflects this situation.
