### ISSUE TITLE
Refactor main loop into smaller functions and files so it's easy to follow.

### ISSUE THREAD

**Issue by sheaivey** [sheaivey/rx5808-pro-diversity#113]

**Comment by Knifa** [comment]
Some general unsorted thoughts around this:

- Ideally split up so states are non-blocking (i.e., no do-while loops for locking in a particular state). Means we can still arrange for other stuff to happen easily (like update RSSI values in one place, do diversity switching in one place, etc.)
- Need a way to deal with button presses centrally given the above. I'm thinking maybe heading towards somehow event based? Not sure how the overhead would work out on this on the AVR chips.

I will try head for literally splitting it up as is for now, though.

**Comment by sheaivey** [comment]
Those are some good goals and are some of the first things I did when creating the La Forge FPV fork as the main loop was a disaster.

**Comment by Knifa** [comment]
Starting to make a go at this now. Keen to hear thoughts on the way I'm doing the state machine.

https://github.com/sheaivey/rx5808-pro-diversity/pull/106/commits/d997e5960d3552a5b208843b3094249bd4bcb920

I wanted to avoid using huge switch statements where possible but I'm aware of the potential issues with memory usage. Still trying to work it out as I'm going along!

**Comment by Knifa** [comment]
https://github.com/sheaivey/rx5808-pro-diversity/pull/106/files#diff-dc7eb18d61c1335e0c1a37dba8755681 good example here too, maybe?

**Comment by Knifa** [comment]
Making good progress on this. Manual, seek, bandscanner and screensaver all working! It's made it so much faster to get stuff working at the very least.

**Comment by Knifa** [comment]
:+1:
