### ISSUE TITLE
Support for RX5809

### ISSUE THREAD

**Issue by paulelsner** [sheaivey/rx5808-pro-diversity#119]
Hi,
is it possible to support this module: http://www.banggood.com/Realacc-RX5809-5_8G-48CH-Diversity-FPV-Receiver-SMA-90-120-Degree-Adapter-For-Fatshark-Goggles-p-1127467.html?rmmds=search

so that features like a band scanner will be available?

**Comment by Knifa** [comment]
I feel like this is probably just the RX5808 module with the name wrong. If you can crack the shielding open and enable SPI you might be able to control it with an Arduino (and then everything would work).

No microcontroller on there though so you'd need to hack it together.

Give it a go!
