### ISSUE TITLE
#USE_FAST_SWITCHING

### ISSUE THREAD

**Issue by njozsef** [sheaivey/rx5808-pro-diversity#120]
https://github.com/gc9n/rx5808-Diversity-RealAcc-Compatible/blob/master/rx5808-pro-diversityGc9n

This link is ported your project.
arduino digital write is slow for two switching (4066 is simple contact, need two 'digital.write' command)
gc9n solution is simply low level  AND and OR command.

Maybe usable this code parts?
THX

/*               codepart from gc9n    */

void setReceiver(uint8_t receiver) {
#ifdef USE_DIVERSITY
  if (receiver == useReceiverA)
  {
#ifdef USE_FAST_SWITCHING
    PORTC = (PORTC & B11111101) | B00000001; //This turns off receiverB_led and turns on receiverA_led simultaniously, this does however breaks the adaptability of receiverA_led/receiverB_led in settings.h
#else
    digitalWrite(receiverB_led, LOW);
    digitalWrite(receiverA_led, HIGH);
#endif
  }
  else
  {
#ifdef USE_FAST_SWITCHING
    PORTC = (PORTC & B11111110) | B00000010; //This turns off receiverA_led and turns on receiverB_led simultaniously
#else
    digitalWrite(receiverA_led, LOW);
    digitalWrite(receiverB_led, HIGH);
#endif
  }
#else
  digitalWrite(receiverA_led, HIGH);
#endif

  active_receiver = receiver;
}

**Comment by Knifa** [comment]
We have a PR #98 for this already but it's blocked on the ultra rewrite #106. Thanks though!
