### ISSUE TITLE
Update while module installed

### ISSUE THREAD

**Issue by 19Gerhard85** [sheaivey/rx5808-pro-diversity#129]
Hey guys,

I have quick question: Is it ok, to update the module while it's installed in the goggles (not powerd up)?

Greets

**Comment by Knifa** [comment]
It depends on your particular module but I would recommend taking it out. The RealAcc version tries to backpower the goggles through the 5V rail (without success!).

**Comment by 19Gerhard85** [comment]
I'm using the Realacc module. Can the backpower damage the googles?

**Comment by Knifa** [comment]
It could make the voltage regulator a little upset, but not sure about real damage. The main problem is that (assuming it's powered over USB) your power source might go overcurrent.

Still strongly advise just taking it out!

**Comment by 19Gerhard85** [comment]
Ok. Thank you very much!
