### ISSUE TITLE
No video output

### ISSUE THREAD

**Issue by teozfrank** [sheaivey/rx5808-pro-diversity#136]
Hi,

I am using the RX5808-pro-basic and I cannot get video to display, I have it wired as shown and have the sketch on my arduino mini. I am using a PAL monitor, could you offer any advice?

Kind Regards,
Frank

**Comment by sheaivey** [comment]
You will need to use Release v1.2 for video instead if you are not using the OLED display.

https://github.com/sheaivey/rx5808-pro-diversity/releases/tag/v1.2

**Comment by teozfrank** [comment]
Ah perfect thank you!

Only problem is, I get a blank screen now instead of no signal, any ideas?

![img_1787](https://cloud.githubusercontent.com/assets/3265598/26804240/29e9d41e-4a3f-11e7-8c4c-c04d19902556.JPG)

**Comment by teozfrank** [comment]
Ok I got it, just needed to press a button and the menu came up, awesome thank you!
