### ISSUE TITLE
Add pulldown resistor to RSSI.

### ISSUE THREAD

**Issue by sheaivey** [sheaivey/rx5808-pro-diversity#27]
In the event a receiver looses power or RSSI gets disconnected this will ensure there are no floating pins on the ATMEGA. This will make sure the other receiver fails over quickly.

**Comment by nathantsoi** [comment]
Building one of these now, any suggestions on how strong to make the pulldown. Seems like 10k might be appropriate?

**Comment by sheaivey** [comment]
I'm using 100k. A 10k allowed to much current to flow to ground and the atmega received a very weak RSSI voltage. 

100k does not mess with the overall RSSI signal very much but does give a true low when RSSI is disconnected.

Good luck with your build!

**Comment by nathantsoi** [comment]
Awesome, 100k it is. Nice work w/ this project. I'm stoked to get mine running.

**Comment by sheaivey** [comment]
I have updated all the images to include the RSSI pulldown resistor.
