### ISSUE TITLE
No diversity gives error when comment out #define USE_DIVERSITY

### ISSUE THREAD

**Issue by Toogo** [sheaivey/rx5808-pro-diversity#43]
If you comment out  #define USE_DIVERSITY you get  error while compiling.

**Comment by sheaivey** [comment]
Thanks for pointing this out... The code now auto detects if diversity is enabled by checking rssiPinB for a value greater then 0 during setup.

The USE_DIVERSITY feature toggle is no longer necessary because of this. I'll leave this issue open as a reminder to remove that setting entirely.

**Comment by Toogo** [comment]
Thank you.

**Comment by sheaivey** [comment]
This has now been fixed.
