### ISSUE TITLE
char const

### ISSUE THREAD

**Issue by chaz762** [sheaivey/rx5808-pro-diversity#44]
I get this error when compiling 

rx5808oled.cpp.o: In function `setup':
/Users/chaz762/rx5808oled.ino:232: undefined reference to `screens::begin(char const*)'
rx5808oled.cpp.o: In function `loop':
/Users/chaz762/rx5808oled.ino:434: undefined reference to `screens::bandScanMode(unsigned char)'
/Users/chaz762/rx5808oled.ino:449: undefined reference to `screens::seekMode(unsigned char)'
/Users/chaz762/rx5808oled.ino:477: undefined reference to `screens::save(unsigned char, unsigned char, unsigned int, char const*)'
/Users/chaz762/rx5808oled.ino:499: undefined reference to `screens::screenSaver(unsigned char, unsigned char, unsigned int, char const*)'
/Users/chaz762/rx5808oled.ino:506: undefined reference to `screens::updateScreenSaver(char, unsigned char, unsigned char, unsigned char)'
/Users/chaz762/rx5808oled.ino:526: undefined reference to `screens::diversity(unsigned char)'
/Users/chaz762/rx5808oled.ino:531: undefined reference to `screens::updateDiversity(char, unsigned char, unsigned char)'
/Users/chaz762/rx5808oled.ino:671: undefined reference to `screens::updateSeekMode(unsigned char, unsigned char, unsigned char, unsigned char, unsigned int, unsigned char, bool)'
/Users/chaz762/rx5808oled.ino:704: undefined reference to `screens::updateBandScanMode(bool, unsigned char, unsigned char, unsigned char, unsigned int, unsigned int, unsigned int)'
/Users/chaz762/rx5808oled.ino:764: undefined reference to `screens::setupMenu()'
/Users/chaz762/rx5808oled.ino:768: undefined reference to `screens::updateSetupMenu(unsigned char, bool, bool, char const*, char)'
/Users/chaz762/rx5808oled.ino:329: undefined reference to `screens::mainMenu(unsigned char)'
rx5808oled.cpp.o: In function `__static_initialization_and_destruction_0':
/Users/chaz762/rx5808oled.ino:52: undefined reference to `screens::screens()'
collect2: error: ld returned 1 exit status
Error compiling.
 I'm a novice but it look like it has to do with the "call_sign" should that be define in setting.h?

**Comment by sheaivey** [comment]
Looks like you have modified the original project and i won't be able to help.

rx5808oled.ino <-- does not exist in the project.

Please checkout the latest master and try compiling again.
