### ISSUE TITLE
New L band

### ISSUE THREAD

**Issue by phoneflex** [sheaivey/rx5808-pro-diversity#65]
it is possible to implement this new band?

Frequency Band L
CH1:5362
CH2:5399
CH3:5436
CH4:5473
CH5:5510
CH6:5547
CH7:5584
CH8:5621

**Comment by yoannwyffels** [comment]
What is this "5.8ghz" band ? Frequencies are very far away from the 5.8ghz spectrum (5800mhz) and may be illegal in most countries around the world...

**Comment by sheaivey** [comment]
Never heard of this L Band and @yoannwyffels makes a good point. Also I'm not sure these RX5808 modules can tune to those frequencies. Also good luck finding a transmitter that will operate in those frequencies.

That said the code change to send the command is pretty simple and you are welcome to run some experiments of your own and report back.
