### ISSUE TITLE
channelTable error for raceband

### ISSUE THREAD

**Issue by bluesign2k** [sheaivey/rx5808-pro-diversity#70]
I believe that there is a typo on the channel table for raceband - specifically channel c5.
The current value is 0x2978, however I believe this will be setting a frequency of 5967 Mhz rather than the 5806 that it is supposed to be. I believe that the correct value should be 0x2987.

**Comment by sheaivey** [comment]
This has been fixed. https://github.com/sheaivey/rx5808-pro-diversity/pull/80
