### ISSUE TITLE
rx5808 gets video signal but Arduino Nano does not display RSSI [Double checked connections]

### ISSUE THREAD

**Issue by chapimp** [sheaivey/rx5808-pro-diversity#72]
I'm not getting RSSI signal with Arduino Nano.

-I know that rx5808 works because I connected to a analog monitor and see video.
-The [A6] pin on the Arduino, I believe it works fine because when I press the pin with my thumb, Arduino starts getting a reading, the harder I press, the higher the reading.

So I'm not sure if it's the rx5808 [rssi] that is not working.
I also tried with a NexWaveRF rx, gets video but no rssi, I found online where the rssi pin was for this rx.

**Comment by sheaivey** [comment]
Sounds like an issue with the RX5808 module not outputting RSSI... A good test would be to change the code and try a different analog pin on your nanoClosing this issue as it is more a problem with your hardware and not with the actual project.
