### ISSUE TITLE
Need better docs

### ISSUE THREAD

**Issue by DavidCheney** [sheaivey/rx5808-pro-diversity#79]
Really not finding anything concise and clear on how to wire and configure.  I'd especially expect something at http://www.laforgefpv.com/, and would help a lot to have it at getfpv.com and your other vendors.

This video does a great job and finding it covered my need:
https://www.youtube.com/watch?v=lQWNvngk0uc
I have no affiliation with the video producer ... just a satisfied viewer.

Loving my LaForge, thanks!

**Comment by sheaivey** [comment]
I'm currently in the process of putting together product manuals for all the La Forge FPV products. They will be uploaded to www.laforge.com website as I complete them.
