### ISSUE TITLE
Support for 2.4GHz video modules

### ISSUE THREAD

**Issue by kolins-cz** [sheaivey/rx5808-pro-diversity#82]
Hello,
would it be possible to code support for RTC6711 IC's? They are also capable of SPI. Looked trough datasheets and SPI registers are of little different design. Not just different values as I expected. As you are familiar with RTC6715, can you decide if 6711 would fit in your project.
Thanks

**Comment by sheaivey** [comment]
This would require different hardware not currently drop in ready for this project.
