### ISSUE TITLE
Start with last channel

### ISSUE THREAD

**Issue by ps915** [sheaivey/rx5808-pro-diversity#85]
Is it possible to let the module start/boot to the last Channel i was using in Manual Mode?
My module always starts on Band E Channel 1, but i always fly Raceband  Channel 3.

**Comment by Schakus** [comment]
You can save the current channel in settings, tune it then settings -> save. Than this channel is the default for boot.

**Comment by ps915** [comment]
missed that! :-D Sorry! Thanks a lot!
