### ISSUE TITLE
Thumbs up! and small change in the contributors list.

### ISSUE THREAD

**Issue by derFrickler** [sheaivey/rx5808-pro-diversity#88]
Great to see how this project evolved! 
Just build a minimum diversity groundstation out of the Banggood Fatshark Oled Module. 

Could you please change my name in the list of contributors from Johann Hermen (should be Johannes anywhay ;-) ) to "der-Frickler.net" which is my alias for all the rc-modeling stuff. 

Thanks a lot and go on!

**Comment by sheaivey** [comment]
I have updated the recognition section as you requested. Thanks for your original contributions!
